name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@09792e32f60bc6b2d18435b687a8d7fd1c5e9f5e # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run knip

      - name: Type check
        run: bun run typecheck

      - name: Unit tests
        run: bun run test:coverage
