name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: kevinmarrec/workflows/.github/workflows/release.yml@6f9db2e9575b217e828c3e7d389c8bfc74260173 # main
    with:
      publish: true
      workflow-cleanup: ci.yml
    permissions:
      actions: write
      contents: write
      id-token: write
