name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: kevinmarrec/workflows/.github/workflows/release.yml@018ce2e468ae3fe3bdea74f5f14ca0f578d59e86 # main
    with:
      publish: true
      workflow-cleanup: ci.yml
    permissions:
      actions: write
      contents: write
      id-token: write
