name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    uses: kevinmarrec/workflows/.github/workflows/release.yml@37167fc6c2a46989d8d2d0366e7e188edafe9a0a # main
    with:
      publish: true
      workflow-cleanup: ci.yml
    permissions:
      actions: write
      contents: write
      id-token: write
